### ISSUE TITLE
Conversion of String Values for AnnotationPropertyValues Fails

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml#82]
Consider the following example:

```xtend
val someString = "java.lang.String"

val annot = omlCommonFactory.createAnnotationPropertyValue
annot.property = someAnnotProperty
annot.value = someString
annot.subject = someSubject
```

When serializing a model containing such a annotation property value, serialization fails with:

```
Error while converting value 'java.lang.String' for grammar rule 'STRING' to string via ValueConverter.
Caused By: org.eclipse.xtext.conversion.ValueConverterException: The value 'java.lang.String' is an invalid UUID
Semantic Object: Extent.modules[0]->TerminologyGraph.boxStatements[0]->Scalar'String'.annotations[0]->AnnotationPropertyValue
```

**Comment by sjiherzig** [comment]
As a followup, when changing the String value to a String that follows the UUID format, then the serialization works just fine. E.g.:

```xtend
val someString = "12341234-1234-1234-1234-123412341234"
```

However, I'm assuming this is not the intended semantics of the value of the AnnotationPropertyValue

**Comment by sjiherzig** [comment]
One more thing: this seems to happen at random. Sometimes the interpretation as STRING works just fine, other times it complains about it not being a UUID.

**Comment by NicolasRouquette** [comment]
I've noticed this odd phenomena as part of fixing #71 where I added a new type, `OML LiteralValue` following the suggestion in the XText doc to use datatype rules instead of terminal rules for parsing values:

https://www.eclipse.org/Xtext/documentation/301_grammarlanguage.html#datatype-rules
 
However, there is a bit of a subtlety here in that a datatype rule must be expressed in terms of terminals, not terminal fragments. Since terminals must be unambiguously parseable in a context-free manner, it means that there must be additional syntactic disambiguation at the level of the datatype rules to gain context-dependent parsing. 

This paradigm is counter-intuitive based on my experience with the powerful [DMS Toolkit](http://semanticdesigns.com/Products/DMS/DMSToolkit.html) because DMS lexers and parsers provide support for context-dependent rules for both lexing and parsing. 

For now, this means that we need unit tests to exercise all possible combinations of values both in terms of parsing and serialization.

**Comment by sjiherzig** [comment]
OK - would a fix for now be to use `LiteralString` instead of `STRING` for now?

**Comment by NicolasRouquette** [comment]
If you use the integration/0.8.0.0 branch, yes; definitely use the `LiteralValue` types.
See for example: https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/blob/integration/0.8.0.0/tests/core/gov.nasa.jpl.imce.oml.dsl.tests/src/gov/nasa/jpl/imce/oml/dsl/tests/OMLDescriptionTest1.xtend#L143

**Comment by sjiherzig** [comment]
Thanks! So if I use a LiteralString it will work? This doesn't seem to be compatible with the grammar: see https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/blob/integration/0.8.0.0/plugins/core/gov.nasa.jpl.imce.oml.dsl/src/gov/nasa/jpl/imce/oml/dsl/OML.xtext#L42

Looks like `value` of `AnnotationPropertyValue` only accepts a `STRING`, which is a terminal.

**Comment by NicolasRouquette** [comment]
Ah, sorry, I got confused with values vs. annotations.

Yes, annotation values are Strings -- both in the metamodel & the grammar.
The problem here is that it is very difficult to ensure that terminals in the grammar are context-free (this is a requirement from Xtext, not from Antlr) as described in the doc:
https://www.eclipse.org/Xtext/documentation/301_grammarlanguage.html#datatype-rules

You can see this when debugging such an example. When serializing a model, Xtext converts the abstract syntax => concrete syntax and for terminals, it also verifies that lexing the terminal yields the same kind of token that was created. This is strange but I suppose it is a way of guaranteeing that the concrete syntax serialization will parse back into the same abstract syntax.
The unfortunate consequence of this is that, basically, all terminals must be parseable in a context-free way. I don't really understand why String and UUID become ambiguous because the terminals are different! A String begins with a quote; A UUID don't have have a quote.

Can you write a simple unit test like I've done before to reproduce this problem?

**Comment by NicolasRouquette** [comment]
I wrote a unit test for this: `OMLAnnotationTest4`.
This test succeeds using the integration/0.8.0.0-based branch:
https://travis-ci.org/JPL-IMCE/gov.nasa.jpl.imce.oml/builds/269063822

Can you please confirm that this unit test works as you also intended?
I suspect the behavior you observed must have been for OML < 0.8

**Comment by sjiherzig** [comment]
I don't see it on the list of unit tests (at https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/tree/integration/0.8.0.0/tests/core/gov.nasa.jpl.imce.oml.dsl.tests/src/gov/nasa/jpl/imce/oml/dsl/tests ). Can you push it?

**Comment by sjiherzig** [comment]
Perhaps it was `OMLAnnotationTest3` that you were referring to - at least it contains a procedure to create an `AnnotationPropertyValue`. As said, I am using the exact same procedure, but it _randomly_ fails when serializing. It seems the serializer sometimes interprets it as a `UUID`, sometimes as a `STRING`. I'm sure that if you run the test multiple times in a row, it will fail occasionally.

**Comment by NicolasRouquette** [comment]
FYI: The link I gave you points to the commit where the unit test is; i.e., on branch [issue-82](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/tree/issue-82)
