### ISSUE TITLE
"No viable alternative at input" for LiteralNumber values that are positive integers

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml#86]
After the transition to OML 0.8.0.0 M4, I had to remove the quotes in the xsd.oml - otherwise I would get parse errors. This is consistent with the grammar, which now expects `LiteralNumber` for `max/minExclusive/Inclusive`. However, there seems to be a problem when trying to interpret positive integers:

```oml
@dc:source="http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#long"
@dc:description="A long is a 6bit integer"
@oml:JavaDatatypeBinding="java.lang.Long"
numericScalarRestriction XSDlong {
	minInclusive -9223372036854775808
	maxInclusive 9223372036854775807
	restrictedRange XSDinteger
}
```

In the above, an error message is thrown in the OML editor for the `maxInclusive` line. The error is "no viable alternative at input". When changing the value to a floating point value (i.e., 9223372036854775807.0), the parser accepts the input.

**Comment by sjiherzig** [comment]
Unfortunately, I am still getting this - even in 0.8.0.0-M24

**Comment by NicolasRouquette** [comment]
Using datatypes helped; however, it is still an incomplete fix.

The problem involves these datatypes in the metamodel:

```
type PositiveIntegerLiteral wraps gov.nasa.jpl.imce.oml.model.datatypes.PositiveIntegerValue

type DecimalDataType wraps gov.nasa.jpl.imce.oml.model.datatypes.DecimalValue
```

In the grammar, these datatypes are used in a context-sensitive manner:

```
...

IRIScalarRestriction returns IRIScalarRestriction:
	( annotations+=AnnotationPropertyValue )*
	'iriScalarRestriction' name=ID
	'{'
		( ('length' length=PositiveIntegerLiteral)? &
		  ('minLength' minLength=PositiveIntegerLiteral)? &
		  ('maxLength' maxLength=PositiveIntegerLiteral)? &
		  ('pattern' pattern=PATTERN)? )
		'restrictedRange' restrictedRange=[DataRange|Reference]
	'}';

NumericScalarRestriction returns NumericScalarRestriction:
	( annotations+=AnnotationPropertyValue )*
	'numericScalarRestriction' name=ID
	'{'
		( ('minInclusive' minInclusive=LiteralNumber)? &
		  ('maxInclusive' maxInclusive=LiteralNumber)? &
		  ('minExclusive' minExclusive=LiteralNumber)? &
		  ('maxExclusive' maxExclusive=LiteralNumber)? )
		'restrictedRange' restrictedRange=[DataRange|Reference]
	'}';
...

PositiveIntegerLiteral returns PositiveIntegerLiteral: 	DIGITS;

LiteralNumber returns LiteralNumber:	
	LiteralReal | LiteralRational | LiteralFloat | LiteralDecimal;
...

LiteralDecimal returns LiteralDecimal:
	{LiteralDecimal} decimal=DIGITS | decimal=DECIMAL;
...

terminal fragment DIGIT:
  '0'..'9';

terminal DIGITS returns PositiveIntegerLiteral:
  DIGIT+;

terminal fragment HEX_LETTER: 
  'a'..'f' | 'A'..'F';

terminal fragment HEX_DIGIT:
  DIGIT | HEX_LETTER;

terminal fragment HEX:
  ('0x'|'0X') (HEX_DIGIT|'_')+ ('#' (('b'|'B')('i'|'I') | ('l'|'L')))?;
	
terminal fragment DEC:
	'-'?
	DIGIT+
	(('e'|'E') ('+'|'-')? DIGIT+)? 
	(('b'|'B')('i'|'I'|'d'|'D') | ('l'|'L'|'d'|'D'|'f'|'F'))?;

terminal DECIMAL returns DecimalDataType:
  DEC | HEX;
```

Ultimately though, there is a *lexical* ambiguity for parsing "9223372036854775807" because it could be lexed as a `DIGITS` token or as a `DECIMAL` token. According to Xtext, the ambiguity is resolved by the order of the terminal rules; so in this case, it is always lexed as a `DIGITS` token.

To solve this problem, the trick involves defining the `gov.nasa.jpl.imce.oml.model.datatypes.PositiveIntegerValue` datatype as a subtype of the `gov.nasa.jpl.imce.oml.model.datatypes.DecimalValue` datatype.

This ensures that, with the `DIGITS` rule having precedence over the `DECIMAL` rule, "9223372036854775807" will be lexed as a `DIGITS` token, which will be a `PositiveIntegeValue`, which is a subtype of a `DecimalValue`.

Finally, it suffixes to relax the rule for parsing `LiteralDecimal` to accept both supertype (`DecimalValue`) and subtype (`PositiveIntegerValue`).
